language: php

php:
  - 5.3
  - 5.4

env:
    - SYMFONY_VERSION=2.1.*
    - SYMFONY_VERSION=2.2.*

before_script:
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION} --dev --prefer-source